/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_BROJOYSTICK_PB_H_INCLUDED
#define PB_BROJOYSTICK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _BroJoystick {
    uint32_t LeftJoy_X;
    uint32_t LeftJoy_Y;
    uint32_t RightJoy_X;
    uint32_t RightJoy_Y;
    uint32_t LeftSlider;
    uint32_t RightSlider;
    bool LeftJoy_Btn;
    bool RightJoy_Btn;
    bool btn1;
    bool btn2;
    bool btn3;
    bool btn4;
    bool sw1;
    bool sw2;
    bool sw3;
} BroJoystick;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define BroJoystick_init_default                 {512u, 512u, 512u, 512u, 0u, 0u, false, false, false, false, false, false, false, false, false}
#define BroJoystick_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BroJoystick_LeftJoy_X_tag                1
#define BroJoystick_LeftJoy_Y_tag                2
#define BroJoystick_RightJoy_X_tag               3
#define BroJoystick_RightJoy_Y_tag               4
#define BroJoystick_LeftSlider_tag               5
#define BroJoystick_RightSlider_tag              6
#define BroJoystick_LeftJoy_Btn_tag              7
#define BroJoystick_RightJoy_Btn_tag             8
#define BroJoystick_btn1_tag                     9
#define BroJoystick_btn2_tag                     10
#define BroJoystick_btn3_tag                     11
#define BroJoystick_btn4_tag                     12
#define BroJoystick_sw1_tag                      13
#define BroJoystick_sw2_tag                      14
#define BroJoystick_sw3_tag                      15

/* Struct field encoding specification for nanopb */
#define BroJoystick_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   LeftJoy_X,         1) \
X(a, STATIC,   REQUIRED, UINT32,   LeftJoy_Y,         2) \
X(a, STATIC,   REQUIRED, UINT32,   RightJoy_X,        3) \
X(a, STATIC,   REQUIRED, UINT32,   RightJoy_Y,        4) \
X(a, STATIC,   REQUIRED, UINT32,   LeftSlider,        5) \
X(a, STATIC,   REQUIRED, UINT32,   RightSlider,       6) \
X(a, STATIC,   REQUIRED, BOOL,     LeftJoy_Btn,       7) \
X(a, STATIC,   REQUIRED, BOOL,     RightJoy_Btn,      8) \
X(a, STATIC,   REQUIRED, BOOL,     btn1,              9) \
X(a, STATIC,   REQUIRED, BOOL,     btn2,             10) \
X(a, STATIC,   REQUIRED, BOOL,     btn3,             11) \
X(a, STATIC,   REQUIRED, BOOL,     btn4,             12) \
X(a, STATIC,   REQUIRED, BOOL,     sw1,              13) \
X(a, STATIC,   REQUIRED, BOOL,     sw2,              14) \
X(a, STATIC,   REQUIRED, BOOL,     sw3,              15)
#define BroJoystick_CALLBACK NULL
#define BroJoystick_DEFAULT (const pb_byte_t*)"\x08\x80\x04\x10\x80\x04\x18\x80\x04\x20\x80\x04\x28\x00\x30\x00\x38\x00\x40\x00\x48\x00\x50\x00\x58\x00\x60\x00\x68\x00\x70\x00\x78\x00\x00"

extern const pb_msgdesc_t BroJoystick_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BroJoystick_fields &BroJoystick_msg

/* Maximum encoded size of messages (where known) */
#define BroJoystick_size                         54

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
